version: 1
newItemTransaction:
  url: http://storage:8090/new/item_transaction
newGunStat:
  url: http://storage:8090/new/gun_stat
events:
  hostname: kafka
  port: 9092
  topic: events
flask:
  host: "0.0.0.0"
  port: 8080