version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    platform: linux/amd64
    ports:
      - "2181"
    hostname: zookeeper
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.13/data

  kafka:
    image: wurstmeister/kafka
    platform: linux/amd64
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" 
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-data:/kafka/kafka-logs
    depends_on:
      - "zookeeper"

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      MYSQL_USER: 'sora'
      MYSQL_PASSWORD: 'sora'
      MYSQL_ROOT_PASSWORD: 'sora'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  audit_log:
    image: soranosuke/audit_log:latest
    platform: linux/amd64
    ports:
      - '8110:8110'
    expose:
      - '8110'
    depends_on:
      - kafka

  receiver:
    image: soranosuke/receiver:latest
    platform: linux/amd64
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - kafka

  storage:
    image: soranosuke/storage:latest
    platform: linux/amd64
    ports:
      - '8090:8090'
    expose:
      - '8090'
    depends_on:
      - kafka
      - db

  processing:
    image: soranosuke/processing:latest
    platform: linux/amd64
    network_mode: host
    ports:
      - '8100:8100'
    expose:
      - '8100'
    depends_on:
      - kafka
      - db
  
  dashboard:
    image: soranosuke/dashboard:latest
    platform: linux/amd64
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - processing
      - audit_log

volumes:
  my-db:
  zookeeper-data:
  kafka-data: